apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: mff
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/100-webserver
    repoURL: https://github.com/osery/2025-12-08-argocd
    targetRevision: "{{ .Values.ArgoCD.Revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
